


export const defaultAdWidgetStyles = {
    dark: {
        styleTitle: 'Dark Style (Default)',
        background: 'black',
        padding: '15px',
        borderRadius: '5px',
        textAlign: 'center',
        fontSize: '14px',
        color: 'rgba(255, 255, 255, 0.8)',
        titleTextColor: 'white',
        logoSize: '22px',
        showLogo: 'flex',
      isDefault: true,
    },
    light: {
        styleTitle: 'Light Style (Default)',
        background: 'white',
        padding: '15px',
        borderRadius: '5px',
        textAlign: 'center',
        fontSize: '14px',
        color: 'rgba(5, 5, 5, 0.8)',
        titleTextColor: 'black',
        logoSize: '22px',
        showLogo: 'flex',
      isDefault: true,
    },
    tealDefault: {
        styleTitle: 'Teal Style (Default)',
        background: 'rgb(0, 36, 36)',
        padding: '15px',
        borderRadius: '5px',
        textAlign: 'center',
        fontSize: '14px',
        color: 'rgba(255, 255, 255, 0.8)',
        titleTextColor: 'rgb(0, 255, 255)',
        logoSize: '22px',
        showLogo: 'flex',
      isDefault: true,
    },
    blueDefault: {
        styleTitle: 'Blue Style (Default)',
        background: 'rgb(0, 0, 128)',
        padding: '15px',
        borderRadius: '5px',
        textAlign: 'center',
        fontSize: '14px',
        color: 'rgba(255, 255, 255, 0.8)',
        titleTextColor: 'rgb(173, 216, 230)',
        logoSize: '22px',
        showLogo: 'flex',
      isDefault: true,
    },
    greenDefault: {
        styleTitle: 'Green Style (Default)',
        background: 'rgb(0, 128, 0)',
        padding: '15px',
        borderRadius: '5px',
        textAlign: 'center',
        fontSize: '14px',
        color: 'rgba(255, 255, 255, 0.8)',
        titleTextColor: 'rgb(144, 238, 144)',
        logoSize: '22px',
        showLogo: 'flex',
      isDefault: true,
    },
    purpleDefault: {
        styleTitle: 'Purple Style (Default)',
        background: 'rgb(75, 0, 130)',
        padding: '15px',
        borderRadius: '5px',
        textAlign: 'center',
        fontSize: '14px',
        color: 'rgba(255, 255, 255, 0.8)',
        titleTextColor: 'rgb(216, 191, 216)',
        logoSize: '22px',
        showLogo: 'flex',
      isDefault: true,
    }
    ,
    redDefault: {
        styleTitle: 'Red Style (Default)',
        background: 'rgb(128, 0, 0)',
        padding: '15px',
        borderRadius: '5px',
        textAlign: 'center',
        fontSize: '14px',
        color: 'rgba(255, 255, 255, 0.8)',
        titleTextColor: 'rgb(255, 99, 71)',
        logoSize: '22px',
        showLogo: 'flex',
      isDefault: true,
    },
    yellowDefault: {
        styleTitle: 'Yellow Style (Default)',
        background: 'rgb(255, 255, 0)',
        padding: '15px',
        borderRadius: '5px',
        textAlign: 'center',
        fontSize: '14px',
        color: 'rgba(0, 0, 0, 0.8)',
        titleTextColor: 'rgb(0, 0, 0)',
        logoSize: '22px',
        showLogo: 'flex',
      isDefault: true,
    },
    pinkDefault: {
        styleTitle: 'Pink Style (Default)',
        background: 'rgb(255, 192, 203)',
        padding: '15px',
        borderRadius: '5px',
        textAlign: 'center',
        fontSize: '14px',
        color: 'rgba(0, 0, 0, 0.8)',
        titleTextColor: 'rgb(255, 20, 147)',
        logoSize: '22px',
        showLogo: 'flex',
      isDefault: true,
    },
    brownDefault: {
        styleTitle: 'Brown Style (Default)',
        background: 'rgb(139, 69, 19)',
        padding: '15px',
        borderRadius: '5px',
        textAlign: 'center',
        fontSize: '14px',
        color: 'rgba(255, 255, 255, 0.8)',
        titleTextColor: 'rgb(210, 180, 140)',
        logoSize: '22px',
        showLogo: 'flex',
      isDefault: true,
    },
};